apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Service name in Docker Compose
    uid: P309CD349E1911F5B
    isDefault: false
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100 # Service name in Docker Compose
    uid: P8E80F9AEF21F6940
    isDefault: true
    jsonData:
      derivedFields:
        # Optional: Links Trace IDs in logs to Tempo (if you use it)
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
